version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage:/var/www/html/storage
      - ./backend/bootstrap/cache:/var/www/html/bootstrap/cache
    ports:
      - "8000:8000"
      - "9000:9000"
    networks:
      - pomolab-network
    depends_on:
      - db
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=pomolab
      - DB_USERNAME=root
      - DB_PASSWORD=password
    command: bash -c "php artisan migrate:fresh --force && php artisan serve --host=0.0.0.0 --port=8000 & php-fpm"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pomolab-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8080
    networks:
      - pomolab-network
    depends_on:
      - app
      - websocket-server
    stdin_open: true
    tty: true

  websocket-server:
    build:
      context: ./websocket-server
      dockerfile: Dockerfile
    container_name: pomolab-websocket
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./websocket-server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - pomolab-network

  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pomolab
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_ROOT_PASSWORD: password 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pomolab-network

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - pomolab-network

volumes:
  postgres_data:
    driver: local

networks:
  pomolab-network:
    driver: bridge
